### ISSUE TITLE
Tried to compile FHIRtoolkit4 and FHIRtoolkit3 but it fails

### ISSUE THREAD

**Issue by dkounal** [HealthIntersections/fhirserver#121]
I tried to compile FHIRtoolkit4 and FHIRtoolkit3 but I think you reorganised a lot of the sources files used in .dpr files and now the toolkits can be compiled. 

Please add also C:\work\fhirserver\dependencies\Indy10 also in projects' search path 

Thank you again for this huge work....

**Comment by dkounal** [comment]
Or it is my fault?

**Comment by grahamegrieve** [comment]
toolkit is deprecated in favour of toolkit2. I'm phasing the code out soon
