### ISSUE TITLE
How to create a resource using the library?

### ISSUE THREAD

**Issue by dkounal** [HealthIntersections/fhirserver#122]
Based on the readme file and by reading the code, I managed to parse Json type resources and read their content.
I noticed that I should cast the 'Element' types based on the provided type.
My problem now is how to create a resource and save it to an JSON or XML format, especially if it is a bundle or something like that.
Can you help me by providing a couple of examples and the methodology of how to create a resource like a Person or a document and a bundle or a searchset?
Thank you in advance

**Comment by grahamegrieve** [comment]
see documentation in library/readme
