### ISSUE TITLE
Obsolete CodeSystem URI in AuditEvent generation

### ISSUE THREAD

**Issue by lawley** [HealthIntersections/fhirserver#139]
https://github.com/HealthIntersections/fhirserver/blob/74d6c04153d63831799f263688b45829939a4ebc/server/operations_r4.pas#L783

Should be http://terminology.hl7.org/CodeSystem/security-source-type I believe.
But also, the code system lists the code "3" as being "Web Server" and "4" as being "Application Server" so either the code or the display are also incorrect.

**Comment by grahamegrieve** [comment]
fixed
