### ISSUE TITLE
support for regex in valuesets

### ISSUE THREAD

**Issue by pat-ryan-health** [HealthIntersections/fhirserver#185]
Valuesets which use regex filters are not supported by the IG Publisher which produces an error on the IG page  like 
" "No Expansion for this valueset (not supported by Publication Tooling )""

and  a qa error like

" Error from server: The filter "code regex [A-Z]{2}" was not understood in the context of urn:iso:std:iso:3166

**Comment by grahamegrieve** [comment]
what exactly is the filter?

**Comment by pat-ryan-health** [comment]
{
        "system": "urn:iso:std:iso:3166",
        "version": "2013",
        "filter": [
          {
            "property": "code",
            "op": "regex",
            "value": "[A-Z]{2}"
          }
        ]
      },

**Comment by grahamegrieve** [comment]
Turns out it's the version that's the problem. where did you get 2013 from?

**Comment by pat-ryan-health** [comment]
Hi Graeme -   I think this was a locally generated codeset, so not available on the terminology server. Sorry for the confusion

**Comment by grahamegrieve** [comment]
it doesn't matter where it is, it's the version = 2013 that's the problem. Does the 2013 bit actually matter?

**Comment by pat-ryan-health** [comment]
It doesn't matter at the moment, because we only hold one version of the country codes. But in the future why might hold multiple versions and we may want to  be able to distinguish them

**Comment by grahamegrieve** [comment]
Well, the server only supports the 2018 version. It won't support 2013 unless someone digs up an instance of the 2013 version

**Comment by pat-ryan-health** [comment]
OK we have a  business requirement to use the 2013 version.
